arb-dir: lib/l10n
template-arb-file: app_en.arb  # This is your main template
output-dir: lib/generated
output-localization-file: app_localizations.dart
preferred-supported-locales: [en, zh, zh_TW]
supported-locales:
  - en
  - zh
  - zh_TW
synthetic-package: true