arb-dir: lib/l10n
template-arb-file: app_en.arb  # This is your main template
output-dir: lib/generated
output-localization-file: app_localizations.dart
preferred-supported-locales: [en, zh_TW, zh, zh_CN, ja, ko]
synthetic-package: true